name: First Workflow

on:
  push:
    branches:
       - main

jobs:
   example_job:
     runs-on: ubuntu-latest

     steps:
        - name: print a welcome massage
          run: echo "echo welcome to our first run"
        - name: checking out the code
          run: actions/checkout@v4.2.2
