name: First Workflow

on:
  push:
    branches:
       - main

jobs:
   example_job:
     runs-on: ubuntu-latest

     steps:
        - name: print a welcome massage
          run: echo "echo welcome to our first run"
